apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-webrtc-gateway-config
  labels:
    app.kubernetes.io/name: webrtc-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.cfg: |
{{ include "webrtc-gateway.config" . | indent 4 }}
