apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" .Release.Name }}
  labels:
    app.kubernetes.io/name: webrtc-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: webrtc-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sip-udp
      port: 5060
      protocol: UDP
      targetPort: 5060
    - name: sip-tcp
      port: 5060
      protocol: TCP
      targetPort: 5060
    - name: sip-tls
      port: 5061
      protocol: TCP
      targetPort: 5061
    - name: prom
      port: 8123
      protocol: TCP
      targetPort: 8123
