name: Install Kamailio-DB Helm Chart
description: 'Install Kamailio-DB Helm Chart'
runs:
  using: 'composite'
  steps:

    - name: Install Kamailio-DB Helm Chart
      shell: bash
      run: |
        helm install kamailio-db \
        oci://ghcr.io/bundasmanu/charts/kamailio-db \
        --version 0.1.0

    - name: Wait 20 secs
      shell: bash
      run: sleep 20

    - name: Check running pods
      shell: bash
      run: |
        kubectl get pods -A | grep kamailio-db
        kubectl describe pods -n default
        kubectl get pvc -n default
        kubectl describe pod kamailio-db-0 -n default
        kubectl logs -n default kamailio-db-0 --tail=300 || true
